services:
  web:
    build: .
    command: pnpm dev
    volumes:
      - .:/app
      - /app/node_modules
    ports: ["3300:3300"]
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
#    depends_on: [db]
#   db:
#     image: mysql:8.4
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: racing
#     volumes:
#       - dbdata:/var/lib/mysql
# volumes:
#   dbdata:
